export default {
  CREATE_USER_ACTION: 'CREATE_USER_ACTION',
  LOGIN_USER_ACTION: 'LOGIN_USER_ACTION',
  USER_LOGOUT: "USER_LOGOUT",

  USERS_REQUEST: 'USERS_REQUEST',
  USERS_RESPONSE: 'USERS_RESPONSE',
  USERS_ERROR: 'USERS_ERROR',

  SAVE_TOKENS_TO_LOCAL: "SAVE_TOKENS_TO_LOCAL",

  GET_USER_ACTION: "GET_USER_ACTION",

  GET_ALL_USERS: "GET_ALL_USERS",


/*  GOODS_ACTION: 'GOODS_ACTION',
  GOODS_RESPONSE: 'GOODS_RESPONSE',
  GOODS_REQUEST: 'GOODS_REQUEST',
  GOODS_ERROR: 'GOODS_ERROR',
  SINGLE_GOODS_ACTION: 'SINGLE_GOODS_ACTION',
  SINGLE_GOODS_RESPONSE: 'SINGLE_GOODS_RESPONSE',
  UPDATE_SINGLE_GOODS_ACTION: 'UPDATE_SINGLE_GOODS_ACTION',*/
};
